# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('persona', models.CharField(max_length=255)),
                ('comentarios', models.TextField(blank=True)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_agua', to='configuracion.Menu')),
                ('ensalada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_ensalada', to='configuracion.Menu')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_entrada', to='configuracion.Menu')),
                ('plato_fuerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_plato_fuerte', to='configuracion.Menu')),
                ('postre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_postre', to='configuracion.Menu')),
            ],
            options={
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
