# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_agua', to='configuracion.Alimento'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='dia',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='ensalada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_ensalada', to='configuracion.Alimento'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_entrada', to='configuracion.Alimento'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='plato_fuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_plato_fuerte', to='configuracion.Alimento'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='postre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_postre', to='configuracion.Alimento'),
        ),
    ]
