# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0002_auto_20160920_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='dia',
            field=models.DateField(),
        ),
    ]
