# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='alimentos')),
                ('tipo', models.CharField(choices=[('ENT', 'ENTRADA'), ('FUE', 'PLATO FUERTE'), ('ENS', 'ENSALADA'), ('POS', 'POSTRE'), ('AGU', 'AGUA')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=140)),
                ('alimentos', models.ManyToManyField(to='configuracion.Alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/restaurantes')),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Restaurante'),
        ),
    ]
