# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='tipo',
            field=models.CharField(choices=[('ENT', 'ENTRADA'), ('FUE', 'PLATO FUERTE'), ('GUA', 'GUARNICION'), ('ENS', 'ENSALADA'), ('POS', 'POSTRE'), ('AGU', 'AGUA')], max_length=3),
        ),
    ]
